language: node_js
node_js:
- '0.12'
- '0.10'
- iojs
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
deploy:
  provider: npm
  email: tparnell8@gmail.com
  api_key:
    secure: epEASzN6wpWqczsq457A0wl4Ts3d4dUOJdsvzHPmiwTC0Jf4YTFW2trmKfy2i1Aal81NfGeLRseuY67uUWQP2yqrSaRqNeP0BEnDRn1EKgTrS0Skk6fFXuDKuXEFciv4ScN5Y/bsFi19rvgJPcy8piREUkXANCXXg91H2PqFiFGjZwm0iSyw02CdDoo+yJ5Fg5T/RnEMtcs6IddZZ+eULDABui96M5wCBKOtujUi3ZjPoZYXqceT0qTl9r66eEmoyGEaOoue3s6kTfrB2Wlvffgd5ijDMZY9FBtzC7ynGcOB81YkFe4mwhoWH/d4deh9CCEaZMHKegEvSQCw+HvStx2bzhFisi5e7flIiPKoECkEirwNgvp7+vybZwnMUuYt1A7GSgHezvCphHlQS4Tkgk9qvdUNwy4yaI3Zw57KN0iPuF3qHkpUyqpQx+ao7J+V+NFthEfH/BCHGw5XBOq/+njSOpzQr6UP0FkeV2ymgRQZiT75MruL6Xu/jssb7umzMtPFBFdYVate2sy8yKtpapV4Pz1MqtwuWJyFUNvkf73akCw0Z2rchiGIJXEkQLQ7ejUyt/DxCMZPqoi8UyWgGGMoCElYSKOyDh8NXa/IQIZHBPTmkDwWgtLyTKp+owZdR4zrasJ4/wIoA2a/eDOl39f/lbZmksd69o7KMkrV5JY=
  on:
    repo: tparnell8/hubot-situation
    branch: master
